<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>StackInspection.Application</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- XML doc wajib untuk DTO (Contracts); class internal lain tidak diwajibkan -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StackInspection.Domain\StackInspection.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
